### PR TITLE
Fix Javadoc

### PR DESCRIPTION
**Pull request by vbauer**

### CODE REVIEW

**Comment by ericleong** [comment]
Thanks!

**Comment by vbauer** [comment]
NP :)

**Comment by ericleong** [comment]
@vbauer hey sorry about this, you also have to sign this [CLA](http://static.tumblr.com/zyubucd/GaTngbrpr/tumblr_corporate_contributor_license_agreement_v1__10-7-14.pdf)

**Comment by vbauer** [comment]
@ericleong Yes, of course. I hope I'll do it today.

**Comment by vbauer** [comment]
JFY: I've just signed CLA and sent it to legal@tumblr.com.

**Comment by ericleong** [comment]
thanks!

**Pull request merged**
